version: "3.8"
services:
  rbac-service:
    build:
      context: .
      dockerfile: Dockerfile.rbac
    ports: 
      - "8001:8000"
    volumes:
      - ./cmd/rbac/rbac-service-example-config.yaml:/go/src/app/cmd/rbac/rbac-service-example-config.yaml
    depends_on: 
      - rbac-db
      - rbac-db-migrator
      - rbacgen
      - nats-streaming
    restart: always 
  
  rbacgen:
    build:
      context: .
      dockerfile: Dockerfile.rbacgen
    ports: 
      - "8002:8000"
    volumes:
      - ./cmd/rbacgen/rbacgen-service-example-config.yaml:/go/src/app/cmd/rbacgen/rbacgen-service-example-config.yaml
    depends_on:
      - rbac-db
      - rbac-db-migrator
      - nats-streaming
    restart: on-failure

  rbac-db:
    image: postgres:12
    ports: 
      - "9001:5432"
    volumes:
      - roles-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superuser
      POSTGRES_DB: roles
    restart: always

  rbac-db-migrator:
    build:
      context: .
      dockerfile: Dockerfile.rbac-db-migrator
    volumes:
      - ./pkg/rbac/repository/postgres/migrations:/migrations
    depends_on:
      - rbac-db
    restart: on-failure

  nats-streaming:
    image: nats-streaming:0.18
    ports: 
      - "4222:4222"
    restart: always

  ims-service:
    build:
      context: .
      dockerfile: Dockerfile.ims
    ports: 
      - "8011:8000"
    volumes:
      - ./cmd/ims/ims-service-example-config.yaml:/go/src/app/cmd/ims/ims-service-example-config.yaml
    depends_on: 
      - ims-db
      - ims-db-migrator
      - nats-streaming
    restart: always 

  ims-db:
    image: postgres:12
    ports: 
      - "9011:5432"
    volumes:
      - ims-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superuser
      POSTGRES_DB: ims
    restart: always
  
  ims-db-migrator:
    build:
      context: .
      dockerfile: Dockerfile.ims-db-migrator
    volumes:
      - ./pkg/ims/repository/postgresql/migrations:/migrations
    depends_on:
      - ims-db
    restart: on-failure
volumes: 
  roles-db:
  ims-db: