dbconnection:
  user: 'postgres'
  password: 'superuser'
  host: 'localhost'
  port: '5432'
  database: 'roles'
  sslmode: 'disable'

mqconnection:
  host: '127.0.0.1'
  port: '4222'
  
pubsub:
  clusterid: 'test-cluster'
  clientid: 'client-id'
  queuename: 'new-queue'
  pingsinterval: 20
  maxunsuccessfulpings: 5
